# Generated by Django 2.1.5 on 2019-03-15 14:00

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cycle',
            name='type_intensive',
            field=models.CharField(blank=True, choices=[('RC', 'Renovação Constante'), ('RCA', 'Renovação Constante + Aeradores'), ('ABAA', 'Água de boa qualidade + Alta renovação + Aeradores')], max_length=4, null=True, verbose_name='Tipo de sistema intensivo'),
        ),
        migrations.AlterField(
            model_name='population',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data'),
        ),
    ]
