# Generated by Django 2.1.5 on 2019-07-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pond',
            name='length',
            field=models.FloatField(verbose_name='Comprimento'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='width',
            field=models.FloatField(verbose_name='Largura'),
        ),
    ]
