# Generated by Django 2.1.5 on 2019-07-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190701_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='system',
            field=models.CharField(choices=[('intensive', 'Intensivo'), ('semi-intensive', 'Semi-Intensivo')], max_length=15, verbose_name='Sistema'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='type_intensive',
            field=models.CharField(blank=True, choices=[('constant-renewal', 'Renovação Constante'), ('constant-renewal-aerators', 'Renovação Constante + Aeradores'), ('water-good-quality-high-renewal-aerators', 'Água de boa qualidade + Alta renovação + Aeradores')], max_length=50, null=True, verbose_name='Tipo de sistema intensivo'),
        ),
    ]
