# Generated by Django 2.1.5 on 2019-02-08 18:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_propriedade_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Propriedade',
            new_name='Property',
        ),
    ]
