# Generated by Django 2.1.5 on 2019-07-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190701_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
