# Generated by Django 2.1.5 on 2019-03-20 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cycle_finalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesca',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data'),
        ),
    ]
