# Generated by Django 2.1.5 on 2019-06-03 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190320_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometria',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='biometria',
            name='middleweight',
            field=models.FloatField(verbose_name='Peso Médio'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='middleweight_despesca',
            field=models.FloatField(choices=[(500, '500'), (600, '600'), (700, '700'), (800, '800'), (900, '900'), (1000, '1000'), (1100, '1100')], verbose_name='Peso Médio'),
        ),
        migrations.AlterField(
            model_name='despesca',
            name='final_middleweight',
            field=models.FloatField(verbose_name='Peso Médio'),
        ),
        migrations.AlterField(
            model_name='population',
            name='middleweight',
            field=models.FloatField(verbose_name='Peso Médio'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(),
        ),
    ]
