# Generated by Django 2.1.5 on 2019-07-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cycle_finalized'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesca',
            old_name='cyle',
            new_name='cycle',
        ),
    ]
