# Generated by Django 2.1.5 on 2019-06-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190403_1335'),
        ('core', '0005_auto_20190603_1134'),
    ]

    operations = [
    ]
