# Generated by Django 2.1.5 on 2019-07-02 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190702_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('price', models.FloatField(verbose_name='Preço')),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cycle')),
            ],
        ),
    ]
