# Generated by Django 2.1.5 on 2019-07-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biometria',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='despesca',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='mortality',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='property',
            name='slug',
        ),
        migrations.AlterField(
            model_name='biometria',
            name='middleweight',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso Médio'),
        ),
    ]
